[project]
name = "ComfyUI"
version = "0.3.27"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"

[project.urls]
homepage = "https://www.comfy.org/"
repository = "https://github.com/comfyanonymous/ComfyUI"
documentation = "https://docs.comfy.org/"

[tool.ruff]
lint.select = [
  "S307", # suspicious-eval-usage
  "S102", # exec
  "T",    # print-usage
  "W",
  # The "F" series in Ruff stands for "Pyflakes" rules, which catch various Python syntax errors and undefined names.
  # See all rules here: https://docs.astral.sh/ruff/rules/#pyflakes-f
  "F",
]
exclude = ["*.ipynb"]

[tool.poetry]
packages = [
    { include = "app"},
]

[[tool.poetry.source]]
name = "torch_cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"
[tool.poetry.dependencies]
torch = {version = "2.1.1", source = "torch_cu121"}
torchvision = {version = "0.16.1", source = "torch_cu121"}
torchaudio = {version = "2.1.1", source = "torch_cu121"}
pyyaml = "^6.0.2"
numpy = "<2"
safetensors = ">=0.4.2"
tqdm = "^4.67.1"
psutil = "^7.0.0"
yarl = ">=1.18.0"
aiohttp = ">=3.11.8"
sentencepiece = "^0.2.0"
tokenizers = ">=0.13.3"
transformers = ">=4.28.1"
einops = "^0.8.1"
torchsde = "^0.2.6"
scipy = "^1.15.2"
comfyui-frontend-package = "1.14.6"
kornia = ">=0.7.1"
spandrel = "^0.4.1"
soundfile = "^0.13.1"
av = "^14.2.0"
